/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_LEADERBOARD_SERVER_H_
#define JSONRPC_CPP_STUB_LEADERBOARD_SERVER_H_

#include <jsonrpccpp/server.h>

class leaderboard_server : public jsonrpc::AbstractServer<leaderboard_server>
{
    public:
        leaderboard_server(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<leaderboard_server>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("submit", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "submission",jsonrpc::JSON_STRING, NULL), &leaderboard_server::submitI);
        }

        inline virtual void submitI(const Json::Value &request, Json::Value &response)
        {
            response = this->submit(request["submission"].asString());
        }
        virtual Json::Value submit(const std::string& submission) = 0;
};

#endif //JSONRPC_CPP_STUB_LEADERBOARD_SERVER_H_
